### PR TITLE
Verbosity and halt command

### PR DESCRIPTION
**Pull request by huseyinkozan**
Added verbose option to launch command.
Added halt command.

### CODE REVIEW

**Comment by johnnyman727** [comment]
@huseyinkozan thanks for contributing! Can you provide a more detailed explanation of what this adds or fixes?

**Comment by huseyinkozan** [comment]
We can do: 
- `t2-vm launch -v` : Starts VM and prints output to command window.
- `t2-vm launch -h` : To show launch options.
- `t2-vm halt` : Power off VM. Also, this have verbosity, too.

**Comment by johnnyman727** [comment]
Looks good to me! Have you signed our [CLA](http://dojofoundation.org/about/claForm)? If not can you do that and ping me once it's submitted? Thanks!

**Comment by huseyinkozan** [comment]
I signed at previous pull request but I forgot how to do it. Are there any directions ?

**Comment by johnnyman727** [comment]
No worries, you only have to sign once!

**Pull request merged**
